export type Question = {
  id: string;
  source: string;
  question: string;
  /** 4~6개. 자격증에 따라 5지선다·6지선다 문항이 있다. */
  choices: string[];
  /** 정답 인덱스. 복수정답 문항은 2~3개가 들어간다. */
  answers: number[];
};

/** JSON 데이터로 들어오는 원본 형태. 단일정답은 `answer`, 복수정답은 `answers`. */
export type RawQuestion = Omit<Question, "answers"> & {
  answer?: number;
  answers?: number[];
};

/** 단일정답 `answer` 표기를 `answers` 배열로 통일한다. */
export function normalizeQuestions(raw: RawQuestion[]): Question[] {
  return raw.map(({ answer, answers, ...rest }) => ({
    ...rest,
    answers: answers ?? (answer === undefined ? [] : [answer]),
  }));
}

const q = (
  id: string,
  source: string,
  question: string,
  choices: [string, string, string, string],
  answer: number,
): Question => ({ id, source, question, choices, answers: [answer] });

export const questions: Question[] = [
  q("p02-01", "p.2 · 1번", "bash에서 export PATH=$PATH:/etc를 실행한 결과는?", ["기존 PATH를 제거한다.", "기존 PATH 뒤에 /etc를 추가한다.", "$PATH라는 새 변수를 만든다.", "명령 자체가 잘못되었다."], 1),
  q("p02-02", "p.2 · 2번", "LILO 부팅 중 'LI'까지만 표시되고 멈추는 원인으로 가장 알맞은 것은?", ["첫 단계 로더가 실행되지 않았다.", "커널 이미지가 손상되었다.", "루트 파일 시스템이 가득 찼다.", "지오메트리 불일치 등으로 두 번째 로더가 잘못된 주소에 적재되었다."], 3),
  q("p02-03", "p.2 · 3번", "여러 디스크나 파티션을 하나로 묶어 구성하는 기술의 조합은?", ["ext4와 LVM", "ext4와 RAID", "ext3와 ext4", "LVM과 RAID"], 3),
  q("p02-04", "p.2 · 4번", "현재 위치가 /home/user1일 때 다른 명령과 이동 결과가 다른 것은?", ["cd ..", "cd /home", "cd ./..", "cd home"], 3),
  q("p02-05", "p.2 · 5번", "users 명령의 기능은?", ["디렉터리 접근 가능 사용자 출력", "현재 로그인 사용자 출력", "현재 사용자의 그룹 출력", "전체 계정의 UID 출력"], 1),
  q("p03-07", "p.3 · 7번", "passwd로 암호를 입력할 때 나타나는 현상은?", ["문자가 그대로 표시된다.", "별표로 표시된다.", "입력 문자가 화면에 표시되지 않는다.", "root만 입력할 수 있다."], 2),
  q("p03-08", "p.3 · 8번", "설치된 리눅스 시스템을 점검·복구할 때 선택하는 메뉴는?", ["Install or upgrade an existing system", "Install system with basic video driver", "Rescue installed system", "Boot from local drive"], 2),
  q("p03-09", "p.3 · 9번", "일반적으로 별도 파티션으로 분리할 영역과 가장 거리가 먼 것은?", ["/etc", "/tmp", "/usr", "/var"], 0),
  q("p03-10", "p.3 · 10번", "네트워크 인터페이스 정보 확인과 관련이 없는 것은?", ["ifconfig", "netstat -l", "cat /etc/crontab", "route"], 2),
  q("p03-11", "p.3 · 11번", "배포판 설치 유형이 아닌 것은?", ["워크스테이션", "업그레이드", "서버", "메인프레임"], 3),
  q("p03-12", "p.3 · 12번", "목적지까지 패킷이 거치는 경로를 확인하는 명령은?", ["traceroute", "ping", "telnet", "ftp"], 0),
  q("p03-13", "p.3 · 13번", "ls 옵션 설명으로 틀린 것은?", ["-a: 숨김 파일 포함", "-l: 대화형 출력", "-R: 하위 디렉터리까지 재귀 출력", "-F: 파일 종류 기호 표시"], 1),
  q("p04-14", "p.4 · 14번", "shutdown 옵션 설명으로 틀린 것은?", ["-c: 예약 취소", "-h: 종료 후 정지", "-f: 종료 전 모든 프로세스에 kill 신호 전달", "-r: 종료 후 재부팅"], 2),
  q("p04-15", "p.4 · 15번", "ihduser의 기본 그룹을 IHD로 변경하는 명령은?", ["usermod -n IHD ihduser", "usermod -g IHD ihduser", "groupmod -n IHD ihduser", "usermod -G ihduser IHD"], 1),
  q("p04-17", "p.4 · 17번", "텍스트에서 특정 패턴과 일치하는 줄을 출력하는 명령은?", ["file", "grep", "less", "find"], 1),
  q("p04-18", "p.4 · 18번", "디스크 일부를 메모리처럼 사용하는 기술은?", ["라이브러리", "스왑", "파이프", "리다이렉션"], 1),
  q("p04-20", "p.4 · 20번", "MBR 파티션 설명으로 틀린 것은?", ["확장 파티션은 한 디스크에 2개 이상 만들 수 있다.", "5개 이상 파티션이 필요하면 확장 파티션을 사용한다.", "논리 파티션은 확장 파티션 안에 만든다.", "주 파티션 항목은 최대 4개다."], 0),
  q("p04-21", "p.4 · 21번", "리처드 스톨먼이 설립한 자유 소프트웨어 관련 단체는?", ["FSF", "ISO", "ANSI", "IETF"], 0),
  q("p05-22", "p.5 · 22번", "mount 옵션 설명으로 맞는 것은?", ["-a: /etc/mtab 항목만 마운트", "-f: 특정 파일 시스템만 마운트", "-n: 마운트 기록을 남기지 않음", "-w: 마운트 해제"], 2),
  q("p05-25", "p.5 · 25번", "전통적 E-IDE Secondary Slave 장치 파일명은?", ["/dev/hda", "/dev/hdb", "/dev/hdc", "/dev/hdd"], 3),
  q("p05-26", "p.5 · 26번", "교육용 유닉스로 리눅스 개발에 영향을 준 운영체제는?", ["MINIX", "Windows 2000", "Mac OS X", "Solaris"], 0),
  q("p05-27", "p.5 · 27번", "표준 입력을 파일로 전환하는 기호는?", ["|", ">", "<", ";"], 2),
  q("p05-28", "p.5 · 28번", "Ubuntu가 기반으로 삼은 배포판은?", ["Fedora", "RHEL", "Debian", "Slackware"], 2),
  q("p06-31", "p.6 · 31번", "리다이렉션 기호가 아닌 것은?", [">", ">>", "<", "~"], 3),
  q("p06-32", "p.6 · 32번", "사용자 계정과 홈 디렉터리를 함께 삭제하는 명령은?", ["userdel ihduser", "userdel -d ihduser", "userdel -r ihduser", "userdel -e ihduser"], 2),
  q("p06-33", "p.6 · 33번", "PWD 환경변수에 저장되는 값은?", ["현재 작업 디렉터리", "홈 디렉터리", "명령 검색 경로", "사용자 암호"], 0),
  q("p06-34", "p.6 · 34번", "국내에서 서버 용도로 개발·배포된 리눅스 배포판은?", ["SULinux", "CentOS", "SUSE", "Fedora"], 0),
  q("p06-35", "p.6 · 35번", "전통적 런레벨에서 텍스트 기반 다중 사용자 모드는?", ["1", "3", "5", "6"], 1),
  q("p07-36", "p.7 · 36번", "지정한 파일의 종류를 판별하는 명령은?", ["what", "file", "type", "tail"], 1),
  q("p07-37", "p.7 · 37번", "텍스트 파일의 앞부분을 출력하는 명령은?", ["head", "tail", "more", "cat"], 0),
  q("p07-38", "p.7 · 38번", "특정 호스트의 IP 주소를 DNS에 질의하는 명령은?", ["dia", "netfind", "nslookup", "vmware"], 2),
  q("p07-40", "p.7 · 40번", "사용자 계정 파일 설명으로 틀린 것은?", ["사용자 생성에는 useradd를 쓴다.", "usermod -d로 홈 경로를 변경할 수 있다.", "그룹 정보는 /etc/group에 저장된다.", "/etc/shadow에 UID와 GID가 저장된다."], 3),
  q("p07-42", "p.7 · 42번", "시스템을 10분 후 재시작하는 명령은?", ["shutdown -r +10", "shutdown -h +10", "shutdown -r 00:10", "shutdown -h 00:10"], 0),
  q("p08-43", "p.8 · 43번", "현재 디렉터리 아래에서 linuxmaster 문자열을 재귀적으로 검색하는 명령은?", ["find . -string linuxmaster", "grep -r linuxmaster .", "ls -al | grep linuxmaster", "cat * | grep linuxmaster"], 1),
  q("p08-44", "p.8 · 44번", "두 파일의 내용을 줄 단위로 비교하는 명령은?", ["find", "break", "diff", "halt"], 2),
  q("p08-46", "p.8 · 46번", "네트워크 파일 공유 기술로 보기 어려운 것은?", ["SMB", "CIFS", "JFS", "NFS"], 2),
  q("p08-50", "p.8 · 50번", "파일·디렉터리 관리 명령이 아닌 것은?", ["cp", "mkdir", "ps", "rm"], 2),

  q("p38-ping", "p.38", "ping으로 직접 확인하기 어려운 것은?", ["원격 호스트 도달 여부", "대략적인 왕복 지연", "로컬 인터페이스 동작 여부", "외부에서 ping 기반 공격을 하는지 여부"], 3),
  q("p38-lilo", "p.38", "LILO와 GRUB 설명으로 틀린 것은?", ["LILO가 GRUB보다 먼저 개발되었다.", "GRUB은 여러 운영체제 부팅을 지원한다.", "GRUB은 다양한 파일 시스템을 이해한다.", "GRUB은 부트 디스크 부팅을 지원하지 않는다."], 3),
  q("p38-shadow", "p.38", "/etc/shadow 설명으로 틀린 것은?", ["일반 사용자는 보통 읽을 수 없다.", "암호 해시와 만료 정보가 저장된다.", "/etc/passwd의 x는 shadow 암호 사용을 나타낸다.", "UID와 기본 GID가 저장된다."], 3),
  q("p39-touch", "p.39 · 6번", "이미 존재하는 a 파일에 touch a를 실행하면?", ["내용이 지워진다.", "기존 파일이 백업된다.", "내용은 유지되고 타임스탬프가 갱신된다.", "오류가 발생한다."], 2),
  q("p39-lilo", "p.39 · 8번", "LILO에 대한 설명으로 틀린 것은?", ["Linux Loader의 약자다.", "네트워크 장치 설정 프로그램이다.", "여러 OS 중 부팅 대상을 고를 수 있다.", "멀티부팅에 사용할 수 있다."], 1),
  q("p40-user", "p.40 · 9번", "일반적인 사용자 관리 명령이 아닌 것은?", ["useradd", "usercreate", "usermod", "userdel"], 1),
  q("p40-groupadd", "p.40 · 13번", "'groupadd: unable to lock group file'의 가장 가능한 원인은?", ["그룹이 이미 생성되었다.", "그룹 파일이 자동 복구되었다.", "권한 부족 또는 잠금 문제로 그룹 생성에 실패했다.", "사용자가 그룹에 추가되었다."], 2),
  q("p41-timeout", "p.41 · 14번", "전통적 LILO 설정 timeout=50의 의미는?", ["0.5초 대기", "5초 대기", "50초 대기", "무한 대기"], 1),
  q("p41-auth", "p.41 · 15번", "리눅스 설치의 사용자 인증 설정과 가장 거리가 먼 것은?", ["MD5 암호", "Shadow Password", "NIS", "SSL 웹 인증서"], 3),
  q("p41-dir", "p.41 · 문제2", "표준 디렉터리 설명으로 틀린 것은?", ["/bin: 기본 명령", "/etc: 시스템 설정", "/opt: 장치 소켓과 로그 전용", "/proc: 커널·프로세스 가상 정보"], 2),
  q("p42-feature", "p.42 · 문제4", "리눅스의 특징으로 틀린 것은?", ["POSIX를 따른다.", "가상 메모리를 지원하지 않는다.", "멀티태스킹을 지원한다.", "네트워크 기능이 뛰어나다."], 1),
  q("p42-netstat", "p.42 · 문제6", "netstat에서 라우팅 테이블을 출력하는 옵션은?", ["-a", "-c", "-i", "-r"], 3),
  q("p42-lilo", "p.42 · 문제8", "LILO 설명으로 틀린 것은?", ["MBR 외 위치에도 설치할 수 있다.", "Red Hat 계열에서만 제공된다.", "여러 OS를 선택해 부팅할 수 있다.", "GRUB도 부트 로더다."], 1),
  q("p42-passwd", "p.42 · 문제9", "Shadow Password 사용 시 /etc/passwd에 직접 저장되지 않는 것은?", ["UID", "GID", "암호 해시", "로그인 셸"], 2),
  q("p43-process", "p.43 · 1번", "xinetd 프로세스만 찾아보는 명령으로 알맞은 것은?", ["ps -ef | grep xinetd", "find / -name xinetd", "free | xinetd", "grep /etc/passwd xinetd"], 0),
  q("p43-env", "p.43 · 3번", "환경 설정과 관련 없는 명령은?", ["unset", "export", "env", "put"], 3),
  q("p43-editor", "p.43 · 4번", "일반적인 리눅스 편집기가 아닌 것은?", ["gedit", "vi", "emacs", "Microsoft Word"], 3),
  q("p43-top", "p.43 · 7번", "CPU·메모리·프로세스를 지속적으로 관찰하는 도구는?", ["pstree", "ps", "free", "top"], 3),
  q("p44-substitution", "p.44 · 8번", "source=$(ls *.c)의 의미는?", [".c 파일을 삭제한다.", "문자열 'ls *.c'를 그대로 저장한다.", "ls *.c 실행 결과를 source 변수에 저장한다.", "두 값을 비교한다."], 2),
  q("p44-builtin", "p.44 · 11번", "셸 내장 키워드가 아닌 것은?", ["ls", "while", "do", "if"], 0),
  q("p44-link", "p.44 · 12번", "링크 설명으로 틀린 것은?", ["하드 링크와 심볼릭 링크가 있다.", "심볼릭 링크는 별도 inode를 쓴다.", "하드 링크는 디렉터리용, 심볼릭 링크는 일반 파일용이다.", "ln -s로 심볼릭 링크를 만든다."], 2),
  q("p45-dns", "p.45 · 13번", "브라우저에서 'unknown host'가 나오면 먼저 점검할 파일은?", ["/etc/host.conf", "/etc/inittab", "/etc/fstab", "/etc/resolv.conf"], 3),
  q("p45-vi", "p.45 · 14번", "vi 명령 설명으로 틀린 것은?", ["a: 커서 뒤에서 입력", "x: 현재 커서의 한 줄 삭제", "cw: 현재 단어 변경", "yy: 현재 줄 복사"], 1),
  q("p45-multitask", "p.45 · 15번", "리눅스 설명으로 틀린 것은?", ["멀티태스킹과 멀티유저 지원", "비선점형 멀티태스킹만 지원", "여러 배포판 존재", "네트워크 운영에 활용"], 1),
  q("p45-kernel", "p.45 · 16번", "커널 역할 설명으로 틀린 것은?", ["하드웨어 입출력을 담당하지 않는다.", "응용 프로그램 실행 환경을 관리한다.", "좁은 의미의 운영체제다.", "하드웨어 자원을 관리한다."], 0),
  q("p46-service", "p.46 · 19번", "인터넷 서비스 설명으로 틀린 것은?", ["TELNET: 원격 단말", "FTP: 파일 송수신", "SMTP: 호스트 이름을 IP로 변환", "HTTP: 웹 문서 전송"], 2),
  q("p46-journal", "p.46", "저널링 파일 시스템이 아닌 것은?", ["ext2", "ext3", "XFS", "JFS"], 0),
  q("p46-year", "p.46", "리눅스 커널이 처음 공개된 해는?", ["1989년", "1991년", "1995년", "2000년"], 1),
  q("p46-ifup", "p.46", "eth1 인터페이스를 활성화하는 전통적 명령은?", ["ifconfig eth1 up", "ifconfig eth1 down", "route eth1 add", "netstat eth1 up"], 0),
  q("p47-free", "p.47 · 1번", "메모리와 스왑 사용량을 확인하는 명령은?", ["df", "du", "free", "top -f"], 2),
  q("p47-shell", "p.47 · 2번", "usermod로 기본 로그인 셸을 변경하는 옵션은?", ["-d", "-g", "-s", "-u"], 2),
  q("p47-boot", "p.47 · 6번", "전통적 PC의 리눅스 부팅 순서로 알맞은 것은?", ["MBR → BIOS → init → 커널", "BIOS → MBR → 커널 → init", "BIOS → 커널 → MBR → init", "init → BIOS → MBR → 커널"], 1),
  q("p54-find", "p.54 · 3번", "이름이 a인 파일이나 디렉터리를 시스템 전체에서 찾는 명령은?", ["locate / -name a", "find / -name a", "wherels / -name a", "grep / -name a"], 1),
  q("p55-output", "p.55 · 6번", "ls -al > more의 실행 결과는?", ["한 페이지씩 출력", "목록을 more라는 파일에 저장", "화면과 파일에 동시 출력", "more 파일 정보 조회"], 1),
  q("p55-cat", "p.55 · 7번", "cat에서 탭·개행 등 제어문자를 표시하는 옵션은?", ["-a", "-b", "-n", "-A"], 3),
  q("p55-du", "p.55 · 8번", "특정 파일이나 디렉터리의 사용 용량을 확인하는 명령은?", ["free", "du", "df", "quota"], 1),
  q("p55-tty", "p.55 · 9번", "현재 터미널의 장치 파일명을 확인하는 명령은?", ["tty", "stty", "term", "xterm"], 0),
  q("p55-locate", "p.55 · 10번", "데이터베이스를 이용해 파일을 빠르게 검색하는 명령은?", ["locate", "grep", "find", "search"], 0),
  q("p55-alias", "p.55 · 11번", "ls에 -alF를 기본 적용하는 올바른 별칭 설정은?", ["alias ls 'ls -alF'", "alias ls='ls -alF'", "unalias ls='ls -alF'", "alias='ls -alF' ls"], 1),
  q("p55-cd", "p.55 · 12번", "홈 디렉터리로 이동하지 않는 명령은?", ["cd", "cd ~", "cd $HOME", "cd HOME"], 3),
  q("p56-ifconfig", "p.56 · 14번", "ifconfig로 확인하기 어려운 정보는?", ["IP 주소", "활성 인터페이스", "패킷 충돌 통계", "목적지까지의 라우터 경로"], 3),
  q("p56-skel", "p.56 · 15번", "새 사용자의 홈에 기본 파일을 제공하는 디렉터리는?", ["/etc/passwd", "/etc/skel", "/etc/login.defs", "/etc/default/useradd"], 1),
  q("p56-sleep", "p.56", "명령 실행을 10초간 지연하는 명령은?", ["wait 10", "sleep 10", "delay 10", "time 10"], 1),
  q("p56-strings", "p.56", "바이너리 파일에서 출력 가능한 문자열을 추출하는 명령은?", ["strings", "grep -b", "cat -A", "file -t"], 0),
  q("p56-uname", "p.56", "현재 커널 릴리스 버전을 확인하는 명령은?", ["uname -r", "kernel -v", "version -k", "hostname -r"], 0),
  q("p56-mail", "p.56", "로그인하지 않은 사용자에게도 메시지를 전달할 수 있는 명령은?", ["write", "talk", "mail", "mesg"], 2),
  q("p56-mesg", "p.56", "터미널 메시지 수신을 거부하는 명령은?", ["mesg n", "write n", "wall n", "mail -n"], 0),
  q("p56-write", "p.56", "로그인한 특정 사용자에게 메시지를 보내는 명령은?", ["wall user", "write user", "mesg user", "mailall user"], 1),
  q("p57-wall", "p.57", "로그인한 모든 사용자에게 메시지를 보내는 명령은?", ["talk", "mesg", "wall", "write"], 2),
  q("p57-cal", "p.57", "옵션 없이 cal을 실행하면 무엇이 출력되는가?", ["오늘 날짜만", "현재 달의 달력", "현재 연도 전체", "시스템 부팅일"], 1),
  q("p57-watch", "p.57", "특정 명령을 일정 간격으로 반복 실행해 결과를 보는 명령은?", ["time", "watch", "repeat", "cronnow"], 1),
  q("p57-midnight", "p.57", "자정에 시스템을 종료하는 명령은?", ["shutdown -h 00:00", "shutdown -r 00:00", "halt +00:00", "poweroff -r 00:00"], 0),
  q("p57-hostname", "p.57", "시스템 호스트명을 확인·변경하는 명령은?", ["host", "hostname", "nslookup", "route"], 1),
  q("p57-mx", "p.57", "nslookup으로 MX 레코드를 조회하는 옵션은?", ["-type=mx", "-mail", "-mxserver", "-record=mail"], 0),
  q("p57-time", "p.57", "명령의 real·user·sys 실행 시간을 측정하는 명령은?", ["date", "watch", "time", "clock"], 2),
  q("p58-hwclock", "p.58", "하드웨어 시계 정보를 확인하는 명령은?", ["date", "hwclock", "rdate", "ntpstat"], 1),
  q("p58-rdate", "p.58", "원격 시간 서버의 시간으로 시스템 시간을 설정하는 전통적 명령은?", ["rdate -s 서버", "rdate -p 서버", "date -r 서버", "hwclock -s 서버"], 0),
  q("p58-wc", "p.58", "wc의 기본 출력 순서는?", ["단어·줄·바이트", "줄·단어·바이트", "바이트·단어·줄", "줄·바이트·단어"], 1),
  q("p58-grepv", "p.58", "grep -v의 기능은?", ["대소문자 무시", "일치하지 않는 줄 출력", "줄 번호 출력", "재귀 검색"], 1),
  q("p58-exec", "p.58", "find가 찾은 각 파일에 명령을 실행할 때 사용하는 옵션은?", ["-run", "-exec", "-pipe", "-apply"], 1),
  q("p58-updatedb", "p.58", "locate가 최근 파일을 찾지 못할 때 먼저 실행할 명령은?", ["finddb", "updatedb", "locate -r", "refreshfs"], 1),
  q("p59-filei", "p.59", "file 명령으로 MIME 형식을 출력하는 옵션은?", ["-a", "-m", "-i", "-t"], 2),
  q("p59-mv", "p.59", "디렉터리를 대상으로 할 때 재귀 옵션 없이도 동작하는 명령은?", ["cp", "rm", "mv", "grep"], 2),
  q("p59-lsr", "p.59", "ls 결과를 역순으로 정렬하는 옵션은?", ["-R", "-r", "-v", "-n"], 1),
  q("p59-whereis", "p.59", "실행 파일·소스·매뉴얼 위치를 함께 찾는 명령은?", ["which", "whereis", "locate -m", "type"], 1),
  q("p59-gshadow", "p.59", "그룹 관리자·암호 정보를 저장하는 파일은?", ["/etc/group", "/etc/passwd", "/etc/gshadow", "/etc/shadow"], 2),
  q("p59-groups", "p.59", "사용자가 속한 그룹을 출력하는 명령은?", ["groups", "groupadd", "who", "id -u"], 0),
  q("p59-passwdd", "p.59", "passwd -d user의 의미는?", ["계정 삭제", "암호 삭제", "홈 삭제", "계정 잠금"], 1),
  q("p59-man5", "p.59", "/etc/passwd의 파일 형식 매뉴얼을 보는 명령은?", ["man passwd", "man 1 passwd", "man 5 passwd", "info /etc/passwd"], 2),
  q("p60-manpath", "p.60", "매뉴얼 검색 경로를 출력하는 명령은?", ["manpath", "whereis man", "which man", "info path"], 0),
  q("p60-info", "p.60", "GNU의 하이퍼텍스트 형식 온라인 매뉴얼 명령은?", ["man", "help", "info", "apropos"], 2),
  q("p60-unalias", "p.60", "설정한 별칭을 제거하는 명령은?", ["unset", "unalias", "alias -d", "removealias"], 1),
  q("p60-which", "p.60", "PATH에서 실제 실행될 명령의 위치를 찾는 명령은?", ["which", "whereis", "find", "file"], 0),
  q("p60-sortn", "p.60", "sort가 문자열 순서가 아닌 숫자값으로 정렬하게 하는 옵션은?", ["-r", "-n", "-f", "-u"], 1),
  q("p60-clear", "p.60", "터미널 화면을 지우는 명령은?", ["clean", "resetall", "clear", "erase"], 2),
  q("p61-init6", "p.61", "나머지 셋과 결과가 다른 명령은?", ["init 6", "halt", "init 0", "poweroff"], 0),
  q("p61-ping", "p.61", "원격 호스트의 도달 여부와 왕복 시간을 확인하는 명령은?", ["ping", "hostname", "route", "ftp"], 0),
  q("p61-cmp", "p.61", "두 파일이 처음 달라지는 바이트 위치를 출력하는 명령은?", ["cmp", "diff", "comm", "cut"], 0),
  q("p61-cut", "p.61", "/etc/passwd에서 ':'를 구분자로 1·3번 필드를 출력하는 명령은?", ["cut -d: -f 1,3 /etc/passwd", "cut -f: 1,3 /etc/passwd", "grep -d: 1,3 /etc/passwd", "awk -d: 1,3 /etc/passwd"], 0),
  q("p61-split", "p.61", "하나의 큰 파일을 여러 작은 파일로 나누는 명령은?", ["divide", "split", "cut", "part"], 1),
  q("p61-grepe", "p.61", "grep에서 확장 정규표현식을 사용하는 옵션은?", ["-v", "-E", "-n", "-c"], 1),
  q("p62-less", "p.62", "상하 이동이 자유로운 페이지 단위 파일 열람 명령은?", ["more", "less", "head", "tail"], 1),
  q("p62-tailf", "p.62", "로그 파일의 새 내용을 계속 확인할 때 쓰는 tail 옵션은?", ["-r", "-n", "-f", "-c"], 2),
  q("p62-append", "p.62", "b.txt 내용을 a.txt 끝에 추가하는 명령은?", ["cat b.txt > a.txt", "cat b.txt >> a.txt", "cat a.txt >> b.txt", "cat a.txt > b.txt"], 1),
  q("p62-find", "p.62", "시스템 전체에서 .txt로 끝나는 대상을 찾고 오류는 버리는 명령은?", ["find / -name '*.txt' 2>/dev/null", "grep / '*.txt' 2>/dev/null", "locate / -name '*.txt'", "find . '*.txt' > /dev/null"], 0),
  q("p62-touch", "p.62", "touch 설명으로 틀린 것은?", ["없는 파일을 만들 수 있다.", "접근·수정 시각을 바꿀 수 있다.", "기존 파일 내용을 유지한다.", "ctime을 임의의 과거 시각으로 직접 설정할 수 있다."], 3),
  q("p62-rmi", "p.62", "rm이 삭제 전에 매번 확인하도록 하는 옵션은?", ["-f", "-i", "-r", "-v"], 1),
  q("p62-cpr", "p.62", "cp로 디렉터리를 재귀 복사하는 옵션은?", ["-i", "-f", "-r", "-a만 가능"], 2),
  q("p63-mkdirp", "p.63", "부모 디렉터리까지 함께 생성하는 mkdir 옵션은?", ["-r", "-p", "-a", "-f"], 1),
  q("p63-groupmod", "p.63", "그룹 kait의 이름을 ihd로 바꾸는 명령은?", ["groupmod -n ihd kait", "groupmod -g ihd kait", "usermod -n ihd kait", "groupadd -n ihd kait"], 0),
  q("p63-chage", "p.63", "암호 만료·날짜 정책을 확인·설정하는 명령은?", ["passwd", "chage", "usermod -p", "shadowctl"], 1),
  q("p63-lock", "p.63", "ihduser의 암호를 잠그는 명령은?", ["passwd -l ihduser", "passwd -d ihduser", "usermod -u ihduser", "chage -l ihduser"], 0),
  q("p63-expire", "p.63", "계정 만료일을 지정하는 usermod 옵션은?", ["-d", "-e", "-g", "-s"], 1),
  q("p63-rename", "p.63", "사용자 로그인 이름을 변경하는 usermod 옵션은?", ["-l", "-u", "-n", "-c"], 0),
  q("p63-logindefs", "p.63", "UID 범위와 암호 정책 등 계정 생성 정책을 담은 파일은?", ["/etc/login.defs", "/etc/default/useradd", "/etc/skel", "/etc/profile"], 0),
  q("p63-su", "p.63", "다른 사용자로 실제 로그인한 것처럼 환경까지 적용하는 su 사용법은?", ["su - 사용자", "su -c 사용자", "su -p 사용자만 가능", "su -n 사용자"], 0),
  q("p64-default", "p.64", "useradd의 기본 홈·그룹·셸 등을 확인하는 파일은?", ["/etc/default/useradd", "/etc/login.defs", "/etc/passwd", "/etc/skel"], 0),
  q("p64-path", "p.64", "PATH 환경변수 값을 올바르게 확인하는 명령은?", ["echo $path", "echo PATH", "echo $PATH", "print PATH()"], 2),
  q("p64-commandpath", "p.64", "명령 실행 파일 검색과 가장 관계가 깊은 환경변수는?", ["HOME", "PATH", "TMOUT", "PWD"], 1),
  q("p64-grubc", "p.64", "GRUB에서 명령행 모드로 들어가는 키는?", ["a", "b", "c", "e"], 2),
  q("p64-run0", "p.64", "시스템 종료를 뜻하는 전통적 런레벨은?", ["0", "1", "5", "6"], 0),
  q("p64-motd", "p.64", "로그인 사용자에게 공지 메시지를 표시하는 파일은?", ["/etc/issue", "/etc/motd", "/etc/fstab", "/etc/profile.d"], 1),
  q("p65-timeout", "p.65", "유휴 사용자의 자동 로그아웃용 TMOUT을 시스템 전체에 설정하기 적절한 파일은?", ["/etc/profile", "/etc/passwd", "/etc/fstab", "/etc/hosts"], 0),
  q("p65-ctrl", "p.65", "현재 실행 중인 명령을 중단할 때 사용하는 키 조합은?", ["Ctrl+C", "Ctrl+D", "Ctrl+L", "Ctrl+Z만 가능"], 0),
  q("p65-run4", "p.65", "전통적으로 사용자 정의 용도로 남겨진 런레벨은?", ["1", "2", "4", "6"], 2),
  q("p65-run1", "p.65", "단일 사용자·복구 모드를 뜻하는 런레벨은?", ["0", "1", "3", "5"], 1),
  q("p65-gruba", "p.65", "전통적 GRUB에서 커널 매개변수를 추가·수정하는 단축키는?", ["a", "b", "c", "d"], 0),
  q("p65-procpart", "p.65", "커널이 인식한 파티션 목록을 보여주는 파일은?", ["/proc/partitions", "/etc/partitions", "/dev/partitions", "/boot/partitions"], 0),
  q("p65-primary", "p.65", "MBR 파티션 테이블의 주·확장 파티션 항목 최대 개수는?", ["2", "4", "8", "16"], 1),
  q("p65-logical", "p.65", "전통적 MBR에서 논리 파티션 번호가 시작되는 값은?", ["1", "3", "4", "5"], 3),
  q("p65-boot", "p.65", "리눅스 커널과 부트 로더 파일이 위치하는 디렉터리는?", ["/bin", "/boot", "/kernel", "/sbin"], 1),
  q("p66-raid", "p.66", "일부 디스크 장애에도 서비스를 계속하려는 목적에 가장 맞는 기술은?", ["LVM만 사용", "RAID 1 또는 RAID 5", "ext2", "swap"], 1),
  q("p66-dhcp", "p.66", "가상 머신에서 IP를 자동 할당받을 때 선택할 방식은?", ["수동 라우팅", "자동(DHCP)", "NFS", "NIS"], 1),
  q("p66-free", "p.66", "설치 디스크에 미할당 공간이 있을 때 사용하는 자동 파티션 메뉴는?", ["여유 공간 사용", "현재 시스템 축소", "전체 디스크 삭제만 가능", "부트 로더 복구"], 0),
  q("p66-virtual", "p.66", "Xen·KVM 가상화 호스트 구성과 관련된 패키지 그룹은?", ["Web Server", "Virtualization Host", "Office Suite", "Print Server"], 1),
  q("p66-hd03", "p.66", "GRUB Legacy의 (hd0,3)이 가리키는 것은?", ["첫 번째 디스크 3번째 파티션", "첫 번째 디스크 4번째 파티션", "네 번째 디스크 첫 파티션", "두 번째 디스크 4번째 파티션"], 1),
  q("p67-timeout", "p.67", "GRUB timeout=10의 의미는?", ["0.1초 대기", "1초 대기", "10초 후 기본 항목 부팅", "10분 후 부팅"], 2),
  q("p67-lvm", "p.67", "여러 디스크를 묶고 논리 볼륨 크기를 유연하게 조정하는 기술은?", ["RAID 0", "LVM", "NFS", "ext4"], 1),
  q("p67-kdump", "p.67", "커널 충돌 시 메모리 정보를 수집해 원인을 분석하도록 돕는 기능은?", ["Kdump", "cron", "LILO", "syslogrotate"], 0),
  q("p67-ntp", "p.67", "네트워크를 통해 날짜와 시간을 동기화하는 프로토콜은?", ["NTP", "NFS", "NIS", "SMTP"], 0),
  q("p67-swapid", "p.67", "전통적 MBR에서 Linux swap 파티션의 유형 ID는?", ["82", "83", "8e", "fd"], 0),
  q("p67-sdb6", "p.67", "/dev/sdb6의 의미로 가장 정확한 것은?", ["두 번째로 인식된 sd 계열 디스크의 6번 파티션", "여섯 번째 디스크의 2번 파티션", "IDE 전용 두 번째 디스크", "스왑 파티션을 뜻함"], 0),
  q("p67-partprobe", "p.67", "파티션을 직접 생성하는 도구가 아니라 변경된 파티션 테이블을 커널에 알리는 명령은?", ["fdisk", "parted", "cfdisk", "partprobe"], 3),
  q("p68-usb", "p.68", "현대 리눅스에서 USB 저장장치가 일반적으로 사용하는 장치명 형식은?", ["/dev/hdX", "/dev/sdX", "/dev/usbX만 가능", "/dev/netX"], 1),
  q("p68-auth", "p.68", "네트워크 사용자 인증 시스템이 아닌 것은?", ["NIS", "LDAP", "Kerberos", "NFS"], 3),
  q("p68-ide", "p.68", "현대 장치명 체계가 나머지와 다른 전통적 디스크 유형은?", ["SATA", "USB 저장장치", "SCSI", "IDE"], 3),
  q("p69-firefox", "p.69", "MPL 라이선스를 대표적으로 사용하는 소프트웨어는?", ["Firefox", "Hadoop", "Linux kernel", "Bash"], 0),
  q("p69-hadoop", "p.69", "Apache License를 대표적으로 사용하는 소프트웨어는?", ["Firefox", "Hadoop", "GNU Emacs", "Linux kernel"], 1),
  q("p69-permissive", "p.69", "수정 소스 공개를 일반적으로 강제하지 않는 조합은?", ["GPL과 AGPL", "Apache와 MIT", "GPL과 LGPL", "MPL과 GPL"], 1),
  q("p69-mpl", "p.69", "MPL 설명으로 틀린 것은?", ["소스 재배포가 가능하다.", "독점 소프트웨어와 결합할 수 있다.", "MPL 파일 수정분은 공개해야 한다.", "결합된 모든 다른 파일도 반드시 공개해야 한다."], 3),
  q("p69-bsd", "p.69", "수정본을 비공개 상용 소프트웨어로 배포할 수 있는 허용적 라이선스는?", ["BSD", "GPL", "AGPL", "GFDL"], 0),
  q("p69-mit", "p.69", "매우 허용적이며 수정본의 소스 비공개가 가능한 라이선스는?", ["MIT", "GPL", "AGPL", "EPL만 가능"], 0),
  q("p69-kali", "p.69", "Debian 기반이며 보안·침투 테스트 도구를 제공하는 배포판은?", ["Kali Linux", "Fedora", "CentOS", "SUSE"], 0),
  q("p69-fedora", "p.69", "Red Hat의 후원을 받는 커뮤니티 중심 배포판은?", ["Fedora", "Debian", "Slackware", "Gentoo"], 0),
  q("p69-thompson", "p.69", "UNIX 초기 개발자로 알맞은 인물은?", ["켄 톰슨", "리누스 토르발스", "리처드 스톨먼", "마크 셔틀워스"], 0),
  q("p70-mint", "p.70", "나머지와 배포판 계열이 다른 것은?", ["CentOS", "Linux Mint", "Oracle Linux", "Scientific Linux"], 1),
  q("p70-dynamic", "p.70", "프로그램 실행 시 필요한 루틴을 가져와 공유하는 기술은?", ["정적 파티션", "동적 라이브러리", "스왑", "파이프"], 1),
  q("p70-lgpl", "p.70", "LGPL 라이브러리를 단순히 링크해 프로그램을 만든 경우의 설명으로 알맞은 것은?", ["프로그램 전체 소스를 반드시 GPL로 공개한다.", "라이브러리 조건을 지키면 프로그램 전체 소스 공개가 강제되지는 않는다.", "상업적 사용이 금지된다.", "재배포가 금지된다."], 1),
  q("p71-gnu", "p.71", "자유롭게 사용할 수 있는 유닉스 호환 운영체제 개발 프로젝트는?", ["GNU", "POSIX", "IETF", "BIOS"], 0),
  q("p71-proc", "p.71", "프로세스·커널 정보를 담는 가상 파일 시스템 디렉터리는?", ["/proc", "/var", "/opt", "/srv"], 0),
  q("p71-lost", "p.71", "파일 시스템 복구 중 발견된 파일 조각이 들어갈 수 있는 디렉터리는?", ["/recovery", "/lost+found", "/var/tmp", "/proc/lost"], 1),
  q("p71-scroll", "p.71", "텍스트 가상 콘솔에서 지나간 화면을 위로 보는 전통적 키 조합은?", ["Shift+PageUp", "Ctrl+PageUp", "Alt+Up", "Ctrl+L"], 0),
  q("p71-console", "p.71", "전통적 가상 콘솔을 전환하는 키 조합의 예는?", ["Alt+F2", "Ctrl+PageDown", "Esc+F2", "Shift+Tab"], 0),
  q("p71-append", "p.71", "표준 출력을 기존 파일 끝에 추가하는 기호는?", [">", ">>", "<", "|"], 1),
  q("p71-pipe", "p.71", "한 프로세스의 표준 출력을 다른 프로세스의 표준 입력으로 연결하는 기호는?", [";", "|", "&", "<>"], 1),
  q("p72-posix", "p.72", "리눅스 특징으로 알맞은 것은?", ["POSIX를 준수한다.", "단일 사용자만 지원한다.", "네트워크 기능이 없다.", "하나의 파일 시스템만 지원한다."], 0),
  q("p72-c", "p.72", "리눅스 커널의 주된 구현 언어는?", ["COBOL", "대부분 C와 일부 어셈블리", "Java만 사용", "Python"], 1),
  q("p72-rhel", "p.72", "대표적인 상용 엔터프라이즈 리눅스 배포판은?", ["RHEL", "MINIX", "FreeDOS", "GNU Hurd"], 0),
  q("p73-caly", "p.73", "cal로 올해 전체 달력을 출력하는 옵션은?", ["-a", "-m", "-s", "-y"], 3),
  q("p73-inittab", "p.73", "전통적 SysV init의 기본 런레벨 설정 파일은?", ["/boot/grub/grub.conf", "/etc/runlevels", "/etc/inittab", "/boot/runlevels"], 2),
  q("p73-icmp", "p.73", "ICMP Echo Request를 이용해 호스트 도달 여부를 검사하는 명령은?", ["login", "route", "ping", "nslookup"], 2),
  q("p73-gpl2", "p.73", "1991년 6월 발표되어 특허·추가 제한 문제를 다룬 GPL 버전은?", ["GPL v1", "GPL v2", "GPL v3", "LGPL"], 1),
  q("p73-lgpl", "p.73", "LGPL 설명으로 틀린 것은?", ["독점 소프트웨어와 결합할 수 있다.", "LGPL 코드 수정분은 공개 대상이 될 수 있다.", "재배포할 수 있다.", "결합한 다른 코드까지 항상 공개해야 한다."], 3),
  q("p74-shrink", "p.74", "설치 공간이 부족해 기존 파티션 크기를 줄이는 메뉴는?", ["현재 시스템 축소하기", "여유 공간 사용", "사용자 레이아웃만 가능", "기존 Linux 시스템 교체"], 0),
  q("p74-fstype", "p.74", "현대 설치 화면의 파일 시스템 유형으로 보기 어려운 것은?", ["ext", "ext4", "vfat", "physical volume (LVM)"], 0),
  q("p74-rdatep", "p.74", "rdate로 원격 서버 시간을 확인만 하는 옵션은?", ["-s", "-t", "-e", "-p"], 3),
  q("p75-cdparent", "p.75", "/usr/local/src에서 cd ..를 실행하면 이동하는 곳은?", ["/", "/usr/local", "/usr/local/src", "사용자 홈"], 1),
  q("p75-cdhome", "p.75", "/usr/local/src에서 인자 없이 cd를 실행하면 이동하는 곳은?", ["/", "/usr/local", "/usr/local/src", "현재 사용자의 홈"], 3),
  q("p75-cdold", "p.75", "/에서 /usr/local/src로 이동한 직후 cd -를 실행하면 어디로 가는가?", ["/", "/usr/local", "/usr/local/src", "사용자 홈"], 0),
  q("p75-grube", "p.75", "GRUB 부트 메뉴에서 선택한 항목의 설정을 편집하는 키는?", ["a", "b", "c", "e"], 3),
  q("p75-init0", "p.75", "나머지와 실행 결과가 다른 명령은?", ["telinit 6", "shutdown -r now", "reboot", "init 0"], 3),
  q("p09-install-type", "p.9 · 2번", "전통적인 리눅스 배포판 설치 유형으로 보기 어려운 것은?", ["워크스테이션", "업그레이드", "서버", "메인프레임"], 3),
  q("p09-grep-v", "p.9 · 3번", "grep -v linuxmaster /etc/passwd의 실행 결과는?", ["linuxmaster가 포함된 행만 출력한다.", "linuxmaster가 포함되지 않은 행만 출력한다.", "linuxmaster 계정을 추가한다.", "파일을 삭제한다."], 1),
  q("p09-wall", "p.9 · 7번", "현재 로그인한 모든 사용자에게 메시지를 보내는 명령은?", ["mail", "wall", "writeall", "talk"], 1),
  q("p10-userdel", "p.10 · 9번", "사용자 계정과 홈 디렉터리를 함께 삭제하는 userdel 옵션은?", ["-r", "-R", "-d", "-D"], 0),
  q("p10-diff-i", "p.10 · 10번", "diff 옵션 설명으로 틀린 것은?", ["-i는 대소문자를 구별한다.", "-b는 연속 공백 차이를 완화해 비교한다.", "-e는 ed 스크립트를 생성한다.", "-w는 모든 공백 차이를 무시한다."], 0),
  q("p10-lsal", "p.10 · 13번", "숨김 파일을 포함해 자세한 목록을 출력하는 ls 옵션 조합은?", ["-c", "-al", "-d", "-dl"], 1),
  q("p11-eject", "p.11 · 15번", "광학 디스크 트레이를 열거나 닫을 때 사용하는 명령은?", ["eject", "mount", "mmd", "close"], 0),
  q("p11-mget", "p.11 · 17번", "대화형 FTP에서 여러 파일을 내려받는 명령은?", ["put", "mput", "get", "mget"], 3),
  q("p11-passwd-x", "p.11 · 18번", "/etc/passwd의 암호 필드가 x일 때의 일반적인 의미는?", ["암호 해시가 /etc/shadow에 별도로 저장된다.", "암호가 문자 x이다.", "계정이 반드시 잠겨 있다.", "암호가 /etc/pass 파일에 저장된다."], 0),
  q("p11-account-default", "p.11 · 21번", "사용자 계정 생성 시 기본 설정 항목으로 보기 어려운 것은?", ["홈 디렉터리", "로그인 셸", "그룹과 GID", "vi 편집기"], 3),
  q("p12-profile", "p.12 · 24번", "시스템 전역 로그인 셸 환경과 PATH를 설정하는 대표 파일은?", ["/etc/profile", "/etc/passwd", "/etc/shadow", "/etc/fstab"], 0),
  q("p13-stderr", "p.13 · 32번", "명령의 표준 오류를 error.log에 저장하는 올바른 형식은?", ["command 0> error.log", "command 1> error.log", "command 2> error.log", "command < error.log"], 2),
  q("p13-ftp-mcopy", "p.13 · 34번", "일반적인 FTP 내부 명령이 아닌 것은?", ["put", "get", "open", "mcopy"], 3),
  q("p14-partition-tool", "p.14 · 37번", "디스크를 논리 구역으로 나누는 작업과 관련 도구의 조합은?", ["MBR와 LILO", "파티션과 fdisk", "파일 시스템과 wall", "스왑과 passwd"], 1),
  q("p15-clear", "p.15 · 46번", "바이너리 파일을 잘못 출력해 흐트러진 터미널 화면을 지우는 기본 명령은?", ["clear", "sweep", "swap", "more"], 0),
  q("p15-primary", "p.15 · 47번", "MBR 파티션 방식에 관한 설명으로 틀린 것은?", ["주 파티션·확장 파티션·논리 파티션을 사용한다.", "주 파티션은 최대 4개 엔트리를 사용할 수 있다.", "확장 파티션 안에 논리 파티션을 만들 수 있다.", "주 파티션은 최대 3개만 만들 수 있다."], 3),
  q("p16-home", "p.16 · 50번", "/home 디렉터리의 일반적인 용도는?", ["커널 이미지 저장", "사용자 홈 디렉터리 저장", "장치 파일 저장", "시스템 로그 저장"], 1),
  q("p17-mount-busy", "p.17", "현재 셸의 작업 디렉터리가 마운트 지점 내부일 때 umount가 실패하는 주된 이유는?", ["장치가 사용 중이기 때문이다.", "파일 시스템이 반드시 손상됐기 때문이다.", "root 계정이기 때문이다.", "마운트가 자동으로 해제됐기 때문이다."], 0),
  q("p17-nslookup", "p.17", "DNS를 통해 호스트 이름의 IP 주소를 조회하는 전통적 명령은?", ["nslookup", "passwd", "free", "diff"], 0),
  q("p17-shutdown10", "p.17", "시스템을 10분 뒤 재부팅하도록 예약하는 명령은?", ["shutdown -h +10", "shutdown -r +10", "reboot -10", "init +10"], 1),
  q("p18-fstab", "p.18", "부팅 시 파일 시스템을 자동 마운트하도록 설정하는 파일은?", ["/etc/fstab", "/etc/profile", "/etc/hosts", "/etc/inittab"], 0),
  q("p18-free", "p.18", "시스템 메모리와 스왑 사용량을 확인하는 명령은?", ["free", "df", "du", "quota"], 0),
  q("p18-redirection", "p.18", "aa 파일이 존재할 때 cat < aa > bb를 실행하면?", ["aa의 내용이 bb에 저장된다.", "bb가 항상 빈 파일이 된다.", "aa가 삭제된다.", "aa와 bb가 서로 교환된다."], 0),
  q("p18-gcc", "p.18", "파일 내용 비교 명령과 가장 관련이 적은 것은?", ["cmp", "diff", "comm", "gcc"], 3),
  q("p18-fdisk", "p.18", "전통적인 텍스트 기반 디스크 파티션 편집 명령은?", ["fdisk", "passwd", "free", "wall"], 0),
  q("p18-permission", "p.18", "-rwxr-xr-x 권한에서 파일 소유자가 할 수 없는 작업은?", ["읽기", "쓰기", "실행", "해당 없음"], 3),
  q("p19-ifdown", "p.19", "ifconfig eth0 down의 의미는?", ["eth0을 비활성화한다.", "eth0을 활성화한다.", "라우팅 테이블을 출력한다.", "호스트명을 eth0으로 바꾼다."], 0),
  q("p19-split", "p.19", "큰 파일을 여러 작은 파일로 나누는 명령은?", ["split", "join", "paste", "merge"], 0),
  q("p19-passwd-user", "p.19", "root가 사용자 choi의 암호를 변경하는 명령은?", ["passwd choi", "passwd -u", "usermod choi", "chage choi"], 0),
  q("p20-rm-i", "p.20", "rm에서 삭제 전에 사용자 확인을 받는 옵션은?", ["-i", "-f", "-r", "-v"], 0),
  q("p20-groupmod-g", "p.20", "그룹 lms의 GID를 700으로 변경하는 명령은?", ["groupmod -g 700 lms", "groupmod -n 700 lms", "usermod -g 700 lms", "groupadd -g lms 700"], 0),
  q("p20-usb-device", "p.20", "현대 리눅스에서 일반적인 USB·SATA 저장장치 파티션의 장치명 예는?", ["/dev/sdb1", "/dev/hdd", "/dev/ttyUSB", "/dev/lp0"], 0),
  q("p20-pipe-temp", "p.20", "셸 파이프에 관한 설명으로 틀린 것은?", ["왼쪽 명령의 표준 출력을 전달한다.", "오른쪽 명령의 표준 입력으로 연결한다.", "| 기호를 사용한다.", "연결할 때마다 디스크에 임시 파일을 반드시 만든다."], 3),
  q("p21-touch", "p.21", "기존 파일의 수정 시각을 현재 시각으로 갱신하는 명령은?", ["touch", "date", "clock", "time"], 0),
  q("p21-kde", "p.21", "리눅스 데스크톱 환경에 해당하는 것은?", ["KDE Plasma", "GRUB", "LILO", "systemd"], 0),
  q("p21-shadow", "p.21", "섀도 패스워드의 암호 해시가 일반적으로 저장되는 파일은?", ["/etc/shadow", "/etc/passwd", "/etc/group", "/etc/profile"], 0),
  q("p22-date", "p.22", "시스템 날짜와 시각을 확인하거나 설정하는 기본 명령은?", ["date", "cal", "clockonly", "time"], 0),
  q("p22-groupdel", "p.22", "groupdel ihd1 실행 시 'group does not exist'가 출력되면?", ["그룹이 없어 삭제하지 못했다.", "그룹이 정상 삭제됐다.", "사용자가 삭제됐다.", "GID가 변경됐다."], 0),
  q("p22-uniq", "p.22", "uniq 명령의 주된 기능은?", ["인접한 중복 행을 걸러내거나 집계한다.", "행을 가나다순으로 정렬한다.", "파일 권한을 변경한다.", "파일 시스템을 검사한다."], 0),
  q("p23-mac", "p.23", "네트워크 인터페이스의 MAC 주소를 확인할 수 있는 현대적 명령은?", ["ip link", "date", "df", "who"], 0),
  q("p23-usermod", "p.23", "이미 존재하는 사용자의 홈·셸·그룹 등을 변경하는 명령은?", ["usermod", "useradd", "userdel", "groupadd"], 0),
  q("p25-vconsole", "p.25", "하나의 물리적 화면에서 여러 텍스트 로그인 화면을 전환하는 기능은?", ["가상 콘솔", "파이프", "스왑", "저널링"], 0),
  q("p25-rmr", "p.25", "rm -r directory의 동작으로 알맞은 것은?", ["디렉터리와 하위 내용을 재귀적으로 삭제한다.", "빈 디렉터리만 삭제한다.", "파일 이름만 바꾼다.", "삭제 전에 항상 백업한다."], 0),
  q("p25-boot", "p.25", "커널과 부트 로더 관련 파일이 주로 위치하는 디렉터리는?", ["/boot", "/home", "/tmp", "/media"], 0),
  q("p25-shell-builtin", "p.25", "셸 내장 명령에 관한 설명으로 틀린 것은?", ["셸 자체가 직접 실행할 수 있다.", "항상 별도의 실행 파일이 필요하다.", "cd가 대표적인 예이다.", "외부 명령보다 프로세스 생성이 적을 수 있다."], 1),
  q("p25-network-file", "p.25", "네트워크 설정과 직접적인 관련이 가장 적은 파일은?", ["/etc/hosts", "/etc/resolv.conf", "/etc/login.defs", "/etc/hostname"], 2),
  q("p25-catn", "p.25", "cat -n foo.txt | more의 결과는?", ["foo.txt에 행 번호를 붙여 페이지 단위로 본다.", "foo.txt를 삭제한다.", "빈 파일을 만든다.", "파일 권한을 표시한다."], 0),
  q("p26-pwdvar", "p.26", "echo $PWD가 출력하는 것은?", ["현재 작업 디렉터리", "사용자 암호", "프로세스 목록", "PATH 전체"], 0),
  q("p26-dush", "p.26", "홈 디렉터리 전체 사용량을 사람이 읽기 쉬운 합계로 확인하는 명령은?", ["du -sh ~", "df -i ~", "free -h ~", "ls -sh /"], 0),
  q("p26-who-count", "p.26", "현재 로그인 세션 수를 행 수로 세는 명령 조합은?", ["who | wc -l", "users | grep -r", "ps | du", "free | wc -c"], 0),
  q("p26-groupadd", "p.26", "GID 510인 ihd 그룹을 생성하는 명령은?", ["groupadd -g 510 ihd", "groupmod -g 510 ihd", "useradd -g 510 ihd", "groupadd ihd -u 510"], 0),
  q("p26-shadow-perm", "p.26", "/etc/shadow의 보안에 관한 설명으로 알맞은 것은?", ["일반 사용자의 읽기를 제한하고 관리자 중심으로 보호한다.", "모든 사용자가 읽고 쓸 수 있다.", "실행 권한이 필수이다.", "웹 서버가 공개한다."], 0),
  q("p26-lsd", "p.26", "ls에서 디렉터리 내용 대신 디렉터리 항목 자체를 표시하는 옵션은?", ["-d", "-a", "-R", "-t"], 0),
  q("p26-journal", "p.26", "저널링 파일 시스템의 핵심 목적은?", ["장애 후 파일 시스템 복구 시간을 줄인다.", "모든 파일을 자동 암호화한다.", "디스크 용량을 무한대로 만든다.", "네트워크 속도를 높인다."], 0),
  q("p26-find-name", "p.26", "루트 아래에서 이름이 정확히 a인 파일과 디렉터리를 찾는 명령은?", ["find / -name a", "grep / a", "locate -r /", "ls / | a"], 0),
  q("p27-mvi", "p.27", "aa가 이미 있을 때 mv -i bb aa를 실행하면?", ["덮어쓰기 여부를 묻는다.", "질문 없이 항상 삭제한다.", "두 파일을 비교만 한다.", "bb를 압축한다."], 0),
  q("p27-ping-limit", "p.27", "ping만으로 직접 확인하기 어려운 것은?", ["호스트 도달 여부", "왕복 시간", "패킷 손실", "상대가 공격을 수행 중인지 여부"], 3),
];
